apiVersion: v1
kind: LimitRange
metadata:
  name: database
spec:
  limits:
   - default:
       memory: 400Mi
       cpu: 400m
     defaultRequest:
       memory: 200Mi
       cpu: 100m
     max:
       memory: 2Gi
       cpu: 1000m
     type: Container
   - max:
       memory: 2Gi
       cpu: 1000m
     type: Pod
