apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-tz-database
  labels:
    config: tz
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /usr/share/zoneinfo/America/Sao_Paulo
