apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-tz
  labels:
    config: tz
spec:
  volumeName: pv-tz-database
  storageClassName: manual
  accessModes:
   - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
