apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-zookeeper
  labels:
    app: zookeeper
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
   - ReadWriteOnce
  hostPath:
    path: /data/zookeeper
