apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-registry
  labels:
    app: registry
spec:
  storageClassName: manual
  capacity:
    storage: 80Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/registry

