apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-registry
  labels:
    app: registry
spec:
  volumeName: pv-registry
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 80Gi
