apiVersion: v1
kind: Service
metadata:
  name: registry
  labels:
    app: registry
spec:
  selector:
    app: registry
  type: NodePort
  ports:
   - port: 443
     targetPort: 443
     nodePort: 30003
