apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubia
  labels:
    app: kubia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubia
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
       - name: kubia
         image: tiger:30003/kubia:alpine
         imagePullPolicy: Always
         ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: kubia
  labels:
    app: kubia
spec:
  selector:
    app: kubia
  type: NodePort
  ports:
   - port: 8080
     targetPort: 8080
     nodePort: 30020
