apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  labels:
    app: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      volumes:
       - name: pv-res
         persistentVolumeClaim:
           claimName: pvc-registry
      containers:
       - name: registry
         image: registry:2
         env:
          - name: REGISTRY_STORAGE_DELETE_ENABLED
            valueFrom:
              configMapKeyRef:
                name: cm-registry
                key: registry.del
          - name: REGISTRY_HTTP_ADDR
            valueFrom:
              configMapKeyRef:
                name: cm-registry
                key: registry.addr
          resources:
            requests:
              cpu: "100m"
              memory: "200Mi"
            limits:
              cpu: "2000m"
              memory: "500Mi"
         volumeMounts:
          - mountPath: /var/lib/registry
            name: pv-res
         ports:
          - containerPort: 5000
