apiVersion: v1
kind: Service
metadata:
  name: registry
  labels:
    app: registry
spec:
  selector:
    app: registry
  type: NodePort
  ports:
   - port: 5000
     targetPort: 5000
     nodePort: 30002
