apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-storage
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"
