apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      volumes:
       - name: pv-redis
         persistentVolumeClaim:
           claimName: pvc-redis
       - name: pvc-zone
         persistentVolumeClaim:
           claimName: pvc-tz
      containers:
      - name: redis
        image: redis:5.0.3-alpine
        command: ["redis-server"]
        args: ["--appendonly", "yes"]
        resources:
           requests:
             cpu: "50m"
             memory: "50Mi"
           limits:
             cpu: "150m"
             memory: "100Mi"
        volumeMounts:
         - mountPath: /data
           name: pv-redis
         - mountPath: /etc/localtime
           name: pvc-zone
        ports:
        - containerPort: 6379
