apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-redis
  labels:
    app: redis
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
   - ReadWriteOnce
  hostPath:
    path: /data/sgdb/redis/data