apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-redis
  labels:
    app: redis
spec:
  volumeName: pv-redis
  storageClassName: manual
  accessModes:
   - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi