apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes:
       - name: pv-post
         persistentVolumeClaim:
           claimName: pvc-postgres
       - name: pvc-zone
         persistentVolumeClaim:
           claimName: pvc-tz
      containers:
      - name: postgres
        image: postgres:10.5-alpine
        env:
         - name: POSTGRES_PASSWORD
           valueFrom:
             secretKeyRef:
               name: s-postgres
               key: password
        volumeMounts:
         - mountPath: /var/lib/postgresql/data
           name: pv-post
         - mountPath: /etc/localtime
           name: pvc-zone
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "2000m"
            memory: "300Mi"
        ports:
        - containerPort: 5432
