apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-postgres
  labels:
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
   - ReadWriteOnce
  hostPath:
    path: /data/sgdb/postgres/data
