apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-postgres
  labels:
    app: postgres
spec:
  volumeName: pv-postgres
  storageClassName: manual
  accessModes:
   - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
