apiVersion: v1
kind: Service
metadata:
  name: kafka-manager
  labels:
    app: kafka-manager
spec:
  selector:
    app: kafka-manager
  type: NodePort
  ports:
   - port: 9000
     targetPort: 9000
     nodePort: 30019
