apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vault
  labels:
    app: vault
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
   - ReadWriteOnce
  hostPath:
    path: /home/thyago/devLabs/data/vault
