apiVersion: v1
kind: Pod
metadata:
  name: task-pv-postgres
spec:
  volumes:
   - name: local-storage-postgres
     persistentVolumeClaim:
       claimName: pvc-postgres
  containers:
   - name: task-pv-postgres
     image: postgres:9.3-alpine
     ports:
      - containerPort: 5432
        name: "http-server"
     volumeMounts:
       - mountPath: "/var/lib/postgresql/data"
         name: local-storage-postgres
