apiVersion: v1
kind: Pod
metadata:
  name: task-pv-volume-postgres
spec:
  volumes:
   - name: vol
     hostPath:
       path: /data/teste
  containers:
   - name: task-pv-volume-postgres
     image: postgres:9.3-alpine
     ports:
      - containerPort: 5432
        name: "http-server"
     volumeMounts:
      - name: vol
        mountPath: /var/lib/postgresql/data
