apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-postgres
spec:
  volumeName: pv-postgres
  storageClassName: manual
  accessModes:
   - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
