apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mongodb
  labels:
    app: mongodb
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
   - ReadWriteOnce
  hostPath:
    path: /data/sgdb/mongodb/data
