apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-consul
  labels:
    app: consul
spec:
  volumeName: pv-consul
  storageClassName: manual
  accessModes:
   - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi