apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-drone
  labels:
    app: drone
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
   - ReadWriteOnce
  hostPath:
    path: /data/drone