apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-drone
  labels:
    app: drone
spec:
  volumeName: pv-drone
  storageClassName: manual
  accessModes:
   - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi