apiVersion: v1
kind: Service
metadata:
  name: drone
  labels:
    app: drone
spec:
  selector:
    app: drone
  type: NodePort
  ports:
   - name: 'http'
     port: 80
     targetPort: 80
     nodePort: 30018
   - name: 'https'
     port: 443
     targetPort: 443
     nodePort: 30019