apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-kafka
  labels:
    app: kafka
spec:
  storageClassName: manual
  capacity:
    storage: 50Gi
  accessModes:
   - ReadWriteOnce
  hostPath:
    path: /data/kafka/logs
