apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-kafka
  labels:
    app: kafka
spec:
  volumeName: pv-kafka
  storageClassName: manual
  accessModes:
   - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
