apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-rabbitmq
  labels:
    app: rabbitmq
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
   - ReadWriteOnce
  hostPath:
    path: /data/rabbitmq
