apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-rabbitmq
  labels:
    app: rabbitmq
spec:
  volumeName: pv-rabbitmq
  storageClassName: manual
  accessModes:
   - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
