apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-dynamodb
  labels:
    app: dynamodb
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
   - ReadWriteOnce
  hostPath:
    path: /data/sgdb/dynamodb/data