apiVersion: v1
kind: Service
metadata:
  name: dynamodb
  labels:
    app: dynamodb
spec:
  selector:
    app: dynamodb
  type: NodePort
  ports:
   - port: 8000
     targetPort: 8000
     nodePort: 30021