apiVersion: v1
kind: Service
metadata:
  name: registry-ui
  labels:
    app: registry-ui
spec:
  selector:
    app: registry-ui
  type: NodePort
  ports:
   - port: 80
     targetPort: 80
     nodePort: 30018